language: node_js
node_js:
  - '0.10'

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable

before_script:
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'npm install'
  - 'bower install'

script:
  - "npm run-script test-ci"

after_script:
  - "npm install coveralls@2.10.0 && cat ./test/coverage/lcov.info | coveralls"

after_success:
  - which google-chrome
  - echo `which google-chrome`