language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower'
  - 'npm install -g grunt-cli'
  - 'npm install'
  - 'bower install'
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./test/coverage/lcov.info | coveralls"